version: '3.8'

services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "2778:2777"  # SMPP frontend for clients
      - "8080:8080"  # Stats page for HAProxy monitoring

  smpp_node0:
    build:
      context: ./smpp-node0
    container_name: smpp_node0
    ports:
      - "2775:2775"

  smpp_node1:
    build:
      context: ./smpp-node1
    container_name: smpp_node1
    ports:
      - "2776:2776"
