version: '3.8'

services:
  smpp-load-balancer:
    image: quarkus/smpp_load_balancer
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: smpp-load-balancer
    ports:
      - "3000:3000"  # Exposing the load balancer port for access
    environment:
      - QUARKUS_PROFILE=dev
      - QUARKUS_DATASOURCE_URL=jdbc:postgresql://smpp-db:5432/smpp_server  # Use service name of the DB container
      - QUARKUS_DATASOURCE_USERNAME=smpp_admin
      - QUARKUS_DATASOURCE_PASSWORD=smpp_password
      - LOADBALANCER_PORT=3000
    depends_on:
      - smpp-db  # Ensure that the database starts first

  smpp-db:
    image: postgres:latest
    container_name: smpp-db
    environment:
      POSTGRES_USER: smpp_admin
      POSTGRES_PASSWORD: smpp_password
      POSTGRES_DB: smpp_server
    ports:
      - "5432:5432"  # Expose PostgreSQL port to the host
    volumes:
      - smpp_db_data:/var/lib/postgresql/data  # Persists database data


volumes:
  smpp_db_data:  # Persists PostgreSQL data between container restarts
