version: '3.8'

services:
  smpp-server-1:
    image: quarkus/smpp_server:latest
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "2775:2775"
    environment:
      smpp.server.name: "SMMP_SERVER_1"
  smpp-server-2:
    image: quarkus/smpp_server:latest
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8081:8080"
      - "2776:2775"
    environment:
      smpp.server.name: "SMMP_SERVER_2"


    networks:
      - smpp-network


networks:
  smpp-network:
    driver: bridge
