apiVersion: v1
kind: Service
metadata:
  name: smpp-server-service
spec:
  type: LoadBalancer  # This creates a load balancer
  selector:
    app: smpp-server
  ports:
    - protocol: TCP
      port: 2775
      targetPort: 2775